config/routes.rb
Rails.application.routes.draw do

  
  get "contacts/new", to: "main#index"
  resources "contacts", only: [:new, :create]
  get "admins/portfolios"
  get "admins/sign_up", to: "admins#index"
  get "admins", to: "admins#index"
  devise_for :admins
  resources :logos
  resources :portfolios
  root "main#index"



end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Message from channedesign.com Website",
      :to => "channe@channedesign.com",
      :from => "channe@channedesign.com"
    }
  end
end

app/models/logo.rb
class Logo < ActiveRecord::Base
	extend CommonScopes
	has_and_belongs_to_many :portfolios

	has_attached_file :image, styles: { thumb: '100x100>' }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	extend CommonScopes
		has_and_belongs_to_many :logos

		has_attached_file :image, styles: { thumb: '100x100>' }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	has_attached_file :image_modal, styles: { thumb: '100x100>' }
  	validates_attachment_content_type :image_modal, :content_type => /\Aimage\/.*\Z/
  	acts_as_list
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!
	layout "admin"
	def index
		
	end

	def portfolios
		@portfolios = Portfolio.order_by_position
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController
	before_action :authenticate_admin!
	layout 'admin'


	def new 
		@logos = Logo.all.includes(:portfolios)
		@logo = Logo.new
	end	

	def create
		@logo = Logo.new(logo_params)

		if @logo.save
			redirect_to admins_portfolios_path, notice: "Logo created successfully"
		else
			render :new, alert: "Logo NOT created"
		end
	end

	def destroy
		Logo.find(params[:id]).destroy
	end

	private
		def logo_params
			params.require(:logo).permit(:title, :image)
		end	
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
		@portfolios = Portfolio.order_by_position
		@contact = Contact.new
	end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/common_scopes.rb
module CommonScopes
	def order_by_position
		order(position: "ASC")
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/work_steps_helper.rb
module WorkStepsHelper
end

app/views/admins/index.html.erb
<div class="col-sm-6">
	<%= link_to("Portfolios", admins_portfolios_path, class: "admin_index_link") %>
</div>
<div class="col-sm-6">
	<%= link_to("Quotes", "", class: "admin_index_link") %>
</div>

app/views/admins/portfolios.html.erb
<div class="col-sm-12 marginBottom50">
	<%= link_to((fa_icon "plus 4x"), new_portfolio_path, class: "btn btn-default") %>
	<%= link_to('Add language', new_logo_path) %>
</div>
<% @portfolios.each do |portfolio| %>
	<% if portfolio.portfolio_type == "Web" %>
		<div class="col-sm-3 marginBottom50">
			<%= link_to(image_tag(portfolio.image, class: "image_100_width portfolios_image"), edit_portfolio_path(portfolio)) %>
		</div>
	<% end %>
	<% if portfolio.portfolio_type == "Logo" || portfolio.portfolio_type == "BigLogo" %>
		<div class="col-sm-3 marginBottom50">
			<%= link_to(image_tag(portfolio.image, class: "image_100_width portfolios_image"), edit_portfolio_path(portfolio)) %>
		</div>
	<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-center">
	<p>2014-<%= Time.now.year %> | &copy; Channe Design</p>
</footer>

app/views/layouts/_navigation.html.erb
<nav id="nav" role="navigation">
	<a href="#home" title="Home"><div class="roundNav active"><i class="fa fa-home fa-2x navIcon" id="homeIcon"></i></div></a><br />
	<a href="#portfolios" title="My Portfolio"><div class="roundNav"><i class="fa fa-briefcase fa-2x navIcon" id="portfolioIcon"></i></div></a><br />
	<a href="#services" title="Services"><div class="roundNav dim"><i class="fa fa-connectdevelop fa-2x navIcon" id="serviceIcon"></i></div></a><br />
	<a href="#work_steps" title="Working with Channe"><div class="roundNav"><i class="fa fa-cogs fa-2x navIcon" id="workIcon"></i></div></a><br />
	<a href="#abouts" title="About Me"><div class="roundNav"><i class="fa fa-child fa-2x navIcon" id="aboutIcon"></i></div></a><br />
	<a href="#contacts" title="Contact Me"><div class="roundNav"><i class="fa fa-envelope-o fa-2x navIcon" id="contactIcon"></i></div></a>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Channe Admin</title>
  <%= favicon_link_tag 'Favicon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="fullHeight">
    <div class="admin_nav_div col-sm-8 col-sm-offset-2 text-center">
      <%= link_to("Website", root_path, class: "btn btn-default") %>
      <%= link_to("Admin", admins_path, class: "btn btn-default") %>
  	 <%= link_to((fa_icon "sign-out"), destroy_admin_session_path, :method => :delete, class: "btn btn-default") %>
    </div>
    <div class="container">
      <div class="row text-center ">
  	     <%= yield %>
      </div>
    </div>
  </div>
	<%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Channe Design, Ruby on Rails Developer, Full Stack Web Developer</title>
  <%= favicon_link_tag 'Favicon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-66495804-2', 'auto');
    ga('send', 'pageview');
  </script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.2/TweenMax.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/animation.gsap.min.js"></script>
  <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
</head>
<body>
  <div class="preloader"></div>
	<%= render "layouts/navigation" %>
	 <%= yield %>
	<%= render "layouts/footer" %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Channe Admin</title>
  <%= favicon_link_tag 'Favicon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="fullHeight">
    <div class="container">
      <div class="row text-center marginTopBottom150">
  	     <%= yield %>
      </div>
    </div>
  </div>
	<%= render "layouts/footer" %>

</body>
</html>

app/views/shared/_logos.html.erb
<%= image_tag("html5.png", class: "logo", id: "logo_html", title: 'HTML5') %>
<%= image_tag("css3.png", class: "logo", id: "logo_css", title: 'CSS3') %>
<%= image_tag("javascript.png", class: "logo", id: "logo_js", title: 'Javascript') %>
<%= image_tag("rwd.png", class: "logo", id: "logo_rwd", title: 'Responsive Web Design') %>
<%= image_tag("bootstrap.png", class: "logo", id: "logo_bs", title: 'Twitter Bootsrap') %>
<%= image_tag("angular.png", class: "logo", id: "logo_angular", title: 'AngularJs') %>
<%= image_tag("rubyonrails.png", class: "logo", id: "logo_ruby", title: 'Ruby On Rails') %>
<%= image_tag("postgresql.png", class: "logo", id: "logo_sql", title: 'Postgresql') %>

app/views/shared/_title_div.html.erb
<div class="container text-center">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 title">
			<h1><%= title %></h1>
			<p class="lead"><%= text %></p>
		</div>
	</div>
</div>